### ISSUE TITLE
make creation of `decomp_2d_setup.log` file optional?

### ISSUE THREAD

**Issue by p-costa** [xcompact3d/2decomp-fft#100]
**Is your feature request related to a problem? Please describe.**
I think many users (myself included) like all the outputs to be lumped into a single log file by redirecting stdout to a file, so I wonder if there could/should be a way to have the output `decomp_2d_setup.log` in stdout? (Perhaps a less verbose option? Though the current level of verbosity seems quite reasonable.)

**Describe a possible solution**
I think something like this would work:

```diff
diff --git a/src/decomp_2d_init_fin.f90 b/src/decomp_2d_init_fin.f90
index fda17fd..d43e1aa 100644
--- a/src/decomp_2d_init_fin.f90
+++ b/src/decomp_2d_init_fin.f90
@@ -213,12 +213,8 @@
     write(fname, "(I0)") nrank ! Adapt to magnitude of nrank
     open(newunit=iounit, file='decomp_2d_setup_'//trim(fname)//'.log', iostat=ierror)
 #else
-    if (nrank == 0) then
-       open(newunit=iounit, file="decomp_2d_setup.log", iostat=ierror)
-    else
-       iounit = output_unit
-       ierror = 0
-    endif
+    iounit = output_unit
+    ierror = 0
 #endif
```
The default output of `decomp_2d_setup.log` would be in stdout, unless in debugging mode, where a filename per task is written. 

Not sure if this is a change you'd like, perhaps it is more a matter of what one is used to. I don't mind just changing my fork instead.

Edit: oh, wow, issue number 100 :tada:

**Comment by mathrack** [comment]
Hello,

Thank you for your suggestion. A more flexible workaround could be a logical / integer flag to control the output ?

The external code calling the library could set the flag to a given value before calling decomp_2d_init.

- Output to stdout
- Output to the file "decomp_2d_setup.log"
- No output

The flag would be skipped for debug builds.

**Comment by p-costa** [comment]
Thank you! Sounds good to me.

> not sure what is the best default setup, output to stdout or "decomp_2d_setup.log"

Outputting to stdout is what other libraries I use do, so I'd vote for stdout as default.

**Comment by mathrack** [comment]
We will try to use this post to vote for the default output ?

thumb up for stdout

thumb down for "decomp_2d_setup.log"

**Comment by p-costa** [comment]
Thanks! If one can tweak the behavior in the external code, the default does not matter so much (to me), though I voted for stdout as default.

**Comment by pbartholomew08** [comment]
No strong opinion either way. As the default has been changed already I would rather keep that as is. We should document how to recover original behaviour so that people are not caught out.
