### ISSUE TITLE
Handling large cases

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/2decomp-fft#107]
**Is your feature request related to a problem? Please describe.**
An Xcompact3d user encountered problems with restarting large (600M+ mesh point) cases. @mathrack identified integer overflow as the likely issue.

**Describe the solution you'd like**
A discussion of how to solve this.

**Describe alternatives you've considered**
Discussion so far has considered:
- Moving to `mpi_f08` for MPI4 large data features
- Rewriting low-level components in C

Both have downsides: `mpi_f08` does not seem well supported by tooling; mixed-language coding is complex/error-prone, however if well-isolated may be the best solution considered so far.

**Comment by mathrack** [comment]
Regarding large cases, the issue at hand is related to reading and writing many files. The displacement offset in bytes tends to overflow, in particular for double precision runs. Using integers with a specific kind when doing operations on the displacement can probably solve this issue without adding low-level C / the `mpi_f08`module (MPI3 / MPI4) .

Regarding very large cases, some similar issues might pop up and switching to low-level C or the mpi_f08 module might be mandatory.

It is now established that the first point is critical for double precision runs below 10^9 grid points. More issues might show up on finer grids, but none is known yet...
