### ISSUE TITLE
Investigate does ADIOS2 require obsolete ``character*(*)`` type?

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/2decomp-fft#116]
> The last warning :
> 
> ```
> 
> src/io.f90(1411): warning #7346: The CHARACTER* form of a CHARACTER declaration is an obsolescent feature in Fortran 2008.
>     character*(*), intent(in) :: varname
> ```
> 
> this is probably just a typo @pbartholomew08 ?

Not a typo - it was the kind ADIOS2 wanted, it's just an old-style of Fortran, will make a note to check whether we can change to something else, but I think leave as is for now

_Originally posted by @pbartholomew08 in https://github.com/xcompact3d/2decomp-fft/issues/115#issuecomment-1340641594_

**Comment by ningli-amd** [comment]
More discussions on this outdated Fortran feature here:

https://fortran-lang.discourse.group/t/what-does-character-mean/330

**Comment by pbartholomew08** [comment]
Testing confirms that `character*(*) -> character(len=*)` appears to be ok
