### ISSUE TITLE
Automate running examples and return success/fail status

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/2decomp-fft#25]
The examples currently must be run manually, we need to automate this for use as a test suite.

To be used as part of a CI the test suite must return a programmatic pass/fail.

**Comment by mathrack** [comment]
This [file](https://github.com/xcompact3d/Incompact3d/blob/compile_intel/.github/workflows/Build.yml) could be a good starting point to check compilation of 2decomp-fft with GNU + OpenMPI and Intel + Intel MPI.

The example with GNU + OpenMPI could be easily adapted to check GNU + MPICH : one should replace `openmpi-bin libopenmpi-dev` with `mpich libmpich-dev`

**Comment by mathrack** [comment]
The PR allowing automatic compilation of the code is a first step towards solving this issue. See https://github.com/xcompact3d/2decomp-fft/pull/39
