### ISSUE TITLE
loading 2decomp as a git submodule

### ISSUE THREAD

**Issue by p-costa** [xcompact3d/2decomp-fft#31]
Dear all,

Thanks for your efforts in improving 2decomp!

I am working on a new version of the code CaNS, and I obviously use 2decomp for the transposes on CPU build and some I/O. I was thinking to fork it (I need to make some changes in the build process for compatibility) and load it as a git submodule. So I wanted to ask you:

* Will this be the main new repo for the up-to-date 2decomp library?
* If so, do you accept some feature requests/suggestions here? Two I have in mind is:
  - Supporting single and double precision transposes in the same build which may be relevant in solvers which need the two;
  - Excluding halo extents for I/O operations (which you may have seen here: https://github.com/numericalalgorithmsgroup/2decomp_fft/issues/4);

Thank you in advance for your reply,
Pedro

PS: for the mixed-precision issue, I am achieving this in my codes using CPP macros, with the following _modus operandi_:

Under a parent module, say, `solver.f90`:
```fortran
module mod_solver
(...)
  interface dgtsv_homebrewed
    module procedure dgtsv_homebrewed_sp,dgtsv_homebrewed_dp
  end interface
contains
(...)
#define MYREAL real(sp)
  subroutine dgtsv_homebrewed_sp(n,a,b,c,p)
#include "solver_dgtsv_homebrewed-inc.f90"
  end subroutine dgtsv_homebrewed_sp
#undef MYREAL
#define MYREAL real(dp)
  subroutine dgtsv_homebrewed_dp(n,a,b,c,p)
#include "solver_dgtsv_homebrewed-inc.f90"
  end subroutine dgtsv_homebrewed_dp
#undef MYREAL
(...)
```

then I have the file `solver_dgtsv_homebrewed-inc.f90` to be `include`d:
```fortran
 !  subroutine dgtsv_homebrewed(n,a,b,c,p)
     implicit none
     integer , intent(in) :: n
     MYREAL, intent(in   ), dimension(:) :: a,b,c
     MYREAL, intent(inout), dimension(:) :: p
     MYREAL, dimension(n) :: d
     MYREAL :: z
     integer :: l
     !
     ! Gauss elimination
     !
     z = 1./(b(1)+eps)
     d(1) = c(1)*z
     p(1) = p(1)*z
     do l=2,n
       z    = 1./(b(l)-a(l)*d(l-1)+eps)
       d(l) = c(l)*z
       p(l) = (p(l)-a(l)*p(l-1))*z
     end do
     !
     ! backward substitution
     !
     do l=n-1,1,-1
       p(l) = p(l) - d(l)*p(l+1)
     end do
 !  end subroutine dgtsv_homebrewed
```

**Comment by pbartholomew08** [comment]
Hi,

1) This will be the new repository for 2decomp&fft
2) We are open to feature requests/suggestions, we are currently working on getting the examples setup as a test suite which will make it easier to collaborate
-- I think supporting single/double would be beneficial, for backwards compatibility we should maintain the primary precision as `mytype`.
-- Although we (I?) don't use halos in Xcompact3d, another project uDALES (https://github.com/uDALES/2decomp-fft) is being ported to 2decomp and is doing some work on the halo implementation, it may be worth discussing this with them.

Thanks for the interest.

**Comment by p-costa** [comment]
Thank you very much for the prompt reply, @pbartholomew08 Paul.

Then I think I will fork this and repo, have it as a git submodule, and keep an eye on it. If you wish to support single/double precision in the same build, you have a tester here (and if I end up implementing it in my fork, I will let you know).

Thanks again for your efforts,
Pedro

PS: From my side, feel free to close the issue if you deem it appropriate.

**Comment by pbartholomew08** [comment]
Glad to be of help, and look forward to collaborating. Please do raise any issues you come across and feel free to open pull requests.
