### ISSUE TITLE
Allow finer control of the debug level

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/2decomp-fft#34]
Currently, when the code is compiled with the debug flag, all the debug checks are active. We could introduce one integer with the save attribute to control the level of verbosity of the debug checks.

1. The default value of the integer is zero in the absence of the debug preprocessor variable. One if it is present.
2. All the debug checks are not compiled if the preprocessor variable is missing
3. Before calling decomp_2d_init, the external code can change the debug level
4. Basic checks are performed when debug value is one
5. Advanced checks and more verbosity when debug value is above one

**Comment by pbartholomew08** [comment]
So a debug check would look something like
```
#ifdef DEBUG
if (debug_level > 3) then ! Value chosen arbitrarily for example
! --- some debugging check
end if
#endif
```
?
I think would still need the ability to compile them out (is that what you mean by point 2?) in case there is a desire to put some test inside a loop.

**Comment by mathrack** [comment]
Yes, the idea of point 2 is that all the debug checks are as follows

```
#ifdef DEBUG
! debug check
#endif
```

However, to avoid printing / checking plenty of stuff when the debug flag is turned on, some error checks would be active only when the debug level is high enough. One could also design some debug checks to be performed only for a given value of the debug level.
