### ISSUE TITLE
Fix update_halo

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/2decomp-fft#48]
[This part of the code](https://github.com/xcompact3d/2decomp-fft/blob/main/src/halo_common.f90#L32) is not very reliable and can produce errors on some cases.

**Comment by pbartholomew08** [comment]
Building tests with `BUILD=debug` confirms there is an error with an out-of bounds access occuring (index 0) - implies halo is not in pencil it thinks it is.

**Comment by pbartholomew08** [comment]
Started #48 to address problem
