### ISSUE TITLE
Check NCCL/CUDA return code

### ISSUE THREAD

**Issue by mathrack** [xcompact3d/2decomp-fft#5]
It would be better to check the return value after the NCCL call.

https://github.com/xcompact3d/2decomp-fft/blob/ed255db9bcdba39a40691d77b8c21d5418eceae9/decomp_2d.f90#L487

It is similar for the CUDA call

https://github.com/xcompact3d/2decomp-fft/blob/ed255db9bcdba39a40691d77b8c21d5418eceae9/decomp_2d.f90#L488

**Comment by pbartholomew08** [comment]
I think we should wait for Stefano to join :)

**Comment by mathrack** [comment]
Can you add https://github.com/rfj82982 to the xcompact3d organization ? Then I can tag him and send him plenty of notifications :-)

**Comment by mathrack** [comment]
NCCL return values should also be checked in the transpose subroutines :

https://github.com/xcompact3d/2decomp-fft/blob/c872323eebf35778a53a96168a3e0cbc7f6d2e04/transpose_x_to_y.f90#L93

**Comment by rfj82982** [comment]
I’ll have a look at this since this might be the problem why the code works only with the old decomp.

**Comment by mathrack** [comment]
Is there any plan to check the error code of the GPU / NCCL calls using `decomp_2d_abort` ? Otherwise, we should close this issue, it is opened for a few months already.

**Comment by mathrack** [comment]
As a side remark, this issue is connected with https://github.com/xcompact3d/2decomp-fft/issues/67
