### ISSUE TITLE
Testing Nvidia on CI takes too long

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/2decomp-fft#66]

**Comment by mathrack** [comment]
See https://github.com/xcompact3d/2decomp-fft/pull/69. Testing Nvidia is still taking long. But this test is performed less often.

**Comment by mathrack** [comment]
Please let me know if the workaround in the PR is sufficient. Otherwise, I guess the only workaround is to remove the test with the nvidia compiler.

**Comment by mathrack** [comment]
The branch https://github.com/xcompact3d/2decomp-fft/tree/split_ci has been updated, I have removed the compilation of examples for the nvidia/GPU and caliper. The CI should no longer have issues. I can open a new PR if the previous was looking like a good solution for the present issue.

**Comment by mathrack** [comment]
I am closing this issue. The CI for the nvidia compiler is taking a long time, but it is no longer running for each commit on a PR on the main branch. Only when merging a PR on the main branch.
