### ISSUE TITLE
Addressing outstanding comments in Nvidia merge

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/2decomp-fft#67]
Thank you ! I will try to look at it deeply shortly. Please update

- [x] the Makefile, I think it does not cover the cufft back-end yet
- [x] the README to describe the GPU / NCCL preprocessor variables and the new optional dependency (cuFFT or cudafor ?)
- [x] Discussion about removing IO test
- [x] please add the profiling statements in fft_cufft.f90, see [here](https://github.com/xcompact3d/2decomp-fft/commit/f7b8af925eee47403c4dca89b2656fea18e595a5#diff-70dbfe04954f7012af26feea2eac3deaae3ec81e2b5bbd381a1d0f01cab6a495) for instance
- [x] please add error checks on each call to cuda functions
- [ ] Discussion about fft test (multiple fft_init and fft_fin in the same program)

Cheers

_Originally posted by @mathrack in https://github.com/xcompact3d/2decomp-fft/issues/63#issuecomment-1259408206_

**Comment by mathrack** [comment]
I will open a PR for the profiling part
