### ISSUE TITLE
Build code with strict flags

### ISSUE THREAD

**Issue by pbartholomew08** [xcompact3d/2decomp-fft#8]
This should help flush out non-standards compliant code and help portability.

With gfortran the compiler can be made very strict with
``
FFLAGS += -Wall -Wpedantic -Wimplicit-interface -Wimplicit-procedure -fcheck=bounds -Werror
``
which will cause compilation to fail in the event of code problems.

**Comment by rfj82982** [comment]
Hi Paul just to understand, do you want to add these flags for compilation or these flags are giving error?

**Comment by pbartholomew08** [comment]
I've added these flags for the GNU build, by default they aren't used you need to do `make BUILD=dev` the idea is to catch coding errors.

They did throw up some "errors" which required minor changes (moving some GPU-only declarations and in an error condition some variables would be unset so they just need to be given a default value).

**Comment by pbartholomew08** [comment]
TODO: Add stricter flags for

- [ ] Intel
- [ ] Cray
- [ ] Nvidia
