### ISSUE TITLE
error for non-periodic bc in y

### ISSUE THREAD

**Issue by CHAPSim** [xcompact3d/2decomp-fft#95]
**Describe the bug**

At line 123 of file src/fft_common.f90
Fortran runtime error: Pointer actual argument 'ph' is not associated

**To Reproduce**
1. Git version - current 
2. Compilation options - DEBUG_BUILD = yes
3. Set-up
error occurs when calling decomp_2d_fft_init(PHYSICAL_IN_Z,nx,ny,nz) in subroutine poisson_010 of incompact3d
At line 123 of file src/fft_common.f90
Fortran runtime error: Pointer actual argument 'ph' is not associated

**Comment by mathrack** [comment]
Hello,
Thank you for reporting this issue. Please share the calling code.
Best regards,
Cédric

**Comment by CHAPSim** [comment]
Hi, 
Thanks for your email.

The calling code is:
Line 716 of the below file
https://github.com/xcompact3d/Incompact3d/blob/master/src/poisson.f90 

Changing 
TYPE(DECOMP_INFO), intent(INOUT) :: decomp
to
TYPE(DECOMP_INFO), intent(OUT) :: decomp
in Line 464 of decomp_2d.f90 does not solve the problem. The same error pops up.

Regards,
Wei

**Comment by mathrack** [comment]
Thank you Wei,

I think our unit tests are currently limited, and we do not yet have a unit test for the FFT engine where the FFT grid is not the main deocmp_2d grid. I will work on a fix. In the meantime, you have two temporary workarounds  : 

- Use https://github.com/xcompact3d/2decomp-fft/commit/1ff48105fc6302fc190007954f42689b98b05148
- Revert the modification in `fft_common.f90` performed in the commit https://github.com/xcompact3d/2decomp-fft/commit/07e78f40f1259415e1079d6cbd8c90e583e9c4d6#diff-34f7f37cb77cc18187f7e2ed3953006bfe572a88007479088f40ae3cd46b1145

**Comment by CHAPSim** [comment]
Hi,

Thanks. 
Revert the modification in `fft_common.f90` works for me.

Regards,
Wei

**Comment by mathrack** [comment]
Hello Wei,
This [PR](https://github.com/xcompact3d/2decomp-fft/pull/96) will probably be merged shortly, it should fix the present issue.
Best,
Cédric
